### ISSUE TITLE
Characters in parameters to filepath not accepted

### ISSUE THREAD

**Issue by Jezzper** [BlackOverlord666/mslinks#12]
This is an actual text in a shortcut target

I:\DXALW32.EXE -cUK "-dI:\;I:\Country\UK"  -uABC

I have then created this

ShellLink sl = ShellLink.createLink("i:\\DXALW32.EXE -cUK \"-dI:\\;I:\\Country\\UK\" -uABC")

but it gives this error:

java.nio.file.InvalidPathException: Illegal char <"> at index 20: i:\DXALW32.EXE -cUK "-dI:\;I:\Country\UK" -uABC

How am I supposed to format the options correctly to make it work?

**Comment by BlackOverlord666** [comment]
Argument of `ShellLink.createLink` supposed to be path to target. If you want command line arguments you should use different function for it, e.g.:
```
ShellLink sl = new ShellLink("I:\DXALW32.EXE");
sl.setCMDArgs("-cUK \"-dI:;I:\Country\UK\" -uABC");
```

**Comment by Jezzper** [comment]
aahh.. thanks :-)

It works now, changed it to:  

ShellLink sl =  ShellLink.createLink("I:\\DXALW32.EXE");
			sl.setCMDArgs("-cUK \"-dI:;I:\\Country\\UK\" -u" + System.getProperty("user.name"))
			.setWorkingDir("i:\\");
			sl.saveTo(System.getProperty("user.home") + "\\Desktop\\"+ "XAL NEW.lnk");
