### ISSUE TITLE
file handle leak

### ISSUE THREAD

**Issue by betafoxy** [BlackOverlord666/mslinks#14]
at ShellLink.java，while file isn't a mslink , in.close() will not execture, so file handle leak !!!
`public ShellLink(InputStream in) throws IOException, ShellLinkException {
        this(new ByteReader(in));
        in.close();
}`

**Comment by BlackOverlord666** [comment]
fixed

**Comment by vatbub** [comment]
I just pushed version 1.0.5 to Maven Central and to JCenter, it should appear there for download shortly
