### ISSUE TITLE
Put mslinks into MavenCentral

### ISSUE THREAD

**Issue by nedtwigg** [BlackOverlord666/mslinks#3]
Hi there!  I think it would be great if mslinks was available in mavencentral.  I've got a template that I use to auto-upload to bintray and mavencentral, add the javadocs to gh-pages, etc.  It would take me about an hour for me to put my fork/ up as "com.diffplug.mslinks".

If you'd like, I can apply the template to your project and you can upload it yourself under your own prefix.

Here's what a project looks like under the template:
https://github.com/diffplug/durian

You'd need to create a Sonatype account, bintray account, and Travis CI account, and the project would use gradle as its build system.  If you're interested in a PR let me know, and if not I'll put it up as "com.diffplug.mslinks" (or something else if you prefer).

**Comment by BlackOverlord666** [comment]
Hi man! Sorry for so slow reply. It seems like good idea but I don't interested now in learning gradle or other things you said.
I have added copyright info to source files, so feel free to put it up as your prefix.

**Comment by nedtwigg** [comment]
Roger.  Thanks for a great lib :)
