### ISSUE TITLE
Index for an icon

### ISSUE THREAD

**Issue by Kwestor** [BlackOverlord666/mslinks#5]
Hi,

I'm using your lib to replace some VB code and I encountered this part:

`IconLocation = "C:\Windows\system32\SHELL32.dll, 131"  `

Can I pass that 131 somehow to `ShellLink`? I tried:

`.setIcon("C:\\Windows\\system32\\SHELL32.dll, 131")`

but it does not work.

**Comment by BlackOverlord666** [comment]
Hi, I'm glad to see you interested in my lib.

ShellLink API doesn't have single setIcon function. You have to use [setIconLocation](https://github.com/BlackOverlord666/mslinks/blob/master/src/mslinks/ShellLink.java#L203) and [setIconIndex](https://github.com/BlackOverlord666/mslinks/blob/master/src/mslinks/ShellLinkHeader.java#L85) in ShellLinkHeader which you can access using [getHeader](https://github.com/BlackOverlord666/mslinks/blob/master/src/mslinks/ShellLink.java#L148) function in ShellLink object.

The first example in readme is showing how to set icon, besides other things.

**Comment by Kwestor** [comment]
Ok, I'm officially blind now. Sorry for bothering you and thanks for the great lib!
