### ISSUE TITLE
Artifact published to maven central

### ISSUE THREAD

**Issue by vatbub** [BlackOverlord666/mslinks#6]
Hey,
I've taken the liberty to publish your library to maven central. That means that a binary distribution is now available for public download [here](http://search.maven.org/#artifactdetails|com.github.vatbub|mslinks|0.0.2|jar) and that means again that it will be much easier for devs to use your library in maven. 

That's it, no further action is required from you, or almost no action. I would be really glad if you could write something along the lines of the beginning of the [readme of my fork](vatbub/mslinks#mslinks) in your readme to tell the world about the artifact on maven central.

Thanks for helping me and have a nice weekend,
vatbub

**Comment by BlackOverlord666** [comment]
Hi, i've updated readme and added link to maven repository page. By the way, someone has already tried to push mslinks to maven, see #3.

**Comment by vatbub** [comment]
Hi, thanks for adding the link to the readme. I saw #3 already but I couldn't find it in maven central so I just published it again.
Greetings,
vatbub

**Comment by vatbub** [comment]
Hey, sorry for disturbing you again. I just republished the artifact on maven central with the version number 1.0.2 (instead of 0.0.2, which matches now your versioning on the releases page). While the old link is still valid, you might want to change it for this link: [http://search.maven.org/#artifactdetails|com.github.vatbub|mslinks|1.0.2|jar](http://search.maven.org/#artifactdetails|com.github.vatbub|mslinks|1.0.2|jar)

Thanks again,
vatbub

**Comment by BlackOverlord666** [comment]
done

**Comment by vatbub** [comment]
Oh, and sorry to disturb you once more ... ;) No, it's not another new link, I just wanted to say thank you :)
Greetings,
vatbub

**Comment by vatbub** [comment]
I'll put v1.0.3 on maven Central later this evening or tomorrow.  Greetings vatbub

**Comment by vatbub** [comment]
I just pushed it to Maven Central, it will appear there in the next couple of minutes.
