### ISSUE TITLE
Target does not change saving to an existing link

### ISSUE THREAD

**Issue by NeilAgg** [BlackOverlord666/mslinks#7]
I am trying to update the target on an existing link using this code:
```
    String one = "C:"+File.separator+"Tmp"+File.separator+"1.txt";  // Already exists
    String two = "C:"+File.separator+"Tmp"+File.separator+"2.txt";  // Already exists
    String link = "C:"+File.separator+"Tmp"+File.separator+"link.txt.lnk";
    ShellLink.createLink(one,link);
    ShellLink slink = new ShellLink(link);
    slink.getLinkInfo().setLocalBasePath(two);
    slink.saveTo(link);
```

At the end of this operation, the link is still pointing to file 1.txt and the program did not generate an error to indicate anything is wrong.  I think the code should either update the link or throw an error telling the user the operation did not complete as anticipated.

**Comment by BlackOverlord666** [comment]
Setting local base path is not enough to define target file location. Primary structure the system uses to determine link target is LinkTargetIDList. In fact, I don't know real reasons for creating so many complicated and duplicated things, i've only created tool for managing it.

I've added separate function for setting target path of ShellLink object using LinkTargetIDList.

**Comment by NeilAgg** [comment]
I see.  Leave it to Microsoft to make things more complicated than they need to be.
I appreciate your adding the function to set the target.  I will update my code to use that.  Thank you.
