### ISSUE TITLE
Ant-Task

### ISSUE THREAD

**Issue by dajos7** [BlackOverlord666/mslinks#8]
Nice feature would be an usable Ant-Task. Many many people are searching for a proper solution for creating lnk files with Ant.

**Comment by vatbub** [comment]
Hey I'm not the repo owner but I had a similar idea which was to publish it on maven central so I just forked the repo and did it myself (see #6). I don't know what would be left to do to use it as a Ant task but we could do it ourselves in a fork.

**Comment by BlackOverlord666** [comment]
Agree with comment above. Feel free to integrate with Ant on your own 😉

**Comment by dajos7** [comment]
That was just an idea also did it myself... but why should everybody do it when a single guy could do it and saves a lot of work for other people.

**Comment by BlackOverlord666** [comment]
I mean you could do it an then share it - does Ant have something like Maven central repository? Also pull requests are welcome. Currently I'm not interested in investigating such stuff (i'm not professional java programmer, i work with other technologies).
