### ISSUE TITLE
Not working compiled project java 1.7

### ISSUE THREAD

**Issue by ecreators** [BlackOverlord666/mslinks#9]
In this time we like to use it, but can't at Java compilation 1.7 because Java 1.8 functions  or lambdas are used.

Please make a **Java 1.7 compiled code version**.

Just avoid lambda, method group calls, streams and defaults in interfaces (constants in interfaces are ok)
Then compile it with Java 1.7 SDK.

Tank you @BlackOverlord666

**Comment by vatbub** [comment]
Hmm, although I'm not the repo owner, I'll try to look into into it later this afternoon. With IntelliJ on my side, it shouldn't be too hard.

**Comment by mikesmiffy128** [comment]
Just a thought: you could possibly run Retrolambda on the mslinks jar as an extra build step.

**Comment by vatbub** [comment]
ok, I just told IntelliJ to compile against 1.7 and it did not show any errors, that means that no changes to the source itself need to be done. Give me a second and I'll compile a 1.7 version for you...

**Comment by vatbub** [comment]
I just uploaded a 1.7 version to my maven snapshot repository. You can download it [here](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/com/github/vatbub/mslinks/1.0.4-SNAPSHOT/mslinks-1.0.4-20170214.152633-10.jar).

If you use maven, you need to add the following repository reference to your pom:
```xml
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.jfrog.org/artifactory/libs-snapshot</url>
    </repository>
</repositories>
```

and then you can add it as a maven dependency:
```xml
<dependency>
    <groupId>com.github.vatbub</groupId>
    <artifactId>mslinks</artifactId>
    <version>1.0.4-20170214.152633-10</version>
</dependency>
```

I didn't push it to maven central yet as I'd like to keep releases on maven central in sync with the releases page of this repo, but once @BlackOverlord666 puts it on the release page, I will push it to maven central too.

Again, no changes to the actual source code were necessary.
Have a nice evening everyone,
vat

**Comment by BlackOverlord666** [comment]
Indeed. I've just compiled it with jdk1.7.0_80. I tried both project settings in IntelliJ IDEA and manual compiling from command line using javac. So I guess you are doing something wrong with your build system.

**Comment by vatbub** [comment]
Ok, I'll then push it to maven centrall too as v1.0.3.1 (maven does not allow to update a jar without a new version number)

**Comment by ecreators** [comment]
thank you very much
